# Generated by Django 4.1.3 on 2022-11-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenUser',
            fields=[
                ('id', models.CharField(default='<function uuid4 at 0x7f4acc4e5f30>', max_length=36, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
