# Generated by Django 4.1.3 on 2022-11-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_routeinfo_alter_genuser_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RouteInfo',
        ),
        migrations.AddField(
            model_name='genuser',
            name='TotalDistance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='genuser',
            name='Username',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='genuser',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='genuser',
            name='id',
            field=models.CharField(default='20d7fe9f-d195-4921-9579-65b964b629ac', max_length=36, primary_key=True, serialize=False),
        ),
    ]
